### ISSUE TITLE
Footer (Presentational)

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/docs.royalnavy.io#151]
https://www.sketch.com/s/97e144f3-9c62-4ffd-8eca-94451b5536e1/a/25GdJk5

<img width="1319" alt="Screenshot 2021-07-13 at 10 53 23" src="https://user-images.githubusercontent.com/48086589/125434153-9f2f2b73-9119-40a6-afca-0390f3158940.png">
<img width="406" alt="Screenshot 2021-07-13 at 10 55 03" src="https://user-images.githubusercontent.com/48086589/125434160-94c3aa56-92c0-46b9-bef6-43a4cef59364.png">

**Comment by thyhjwb6** [comment]
The mobile version of this component has been split out into #169
