### ISSUE TITLE
In the "On this Page" Section on the RHS, clicking on a heading takes you to about 3 lines below that heading title

### ISSUE THREAD

**Issue by KxDm8** [Royal-Navy/docs.royalnavy.io#299]

**Comment by KxDm8** [comment]
![image](https://user-images.githubusercontent.com/85285183/134310974-e7389d08-a626-4b7a-b2a8-6a7760ede310.png)

**Comment by KxDm8** [comment]
Instead of: 
![image](https://user-images.githubusercontent.com/85285183/134311076-1826d568-36fd-4c49-9032-421c56b8aad9.png)

**Comment by hxltrhuxze** [comment]
Fix: needs negative margins applied to headings to offset the fixed masthead
